export const FIND_OR_CREATE_USER_SUCCESS = 'FIND_OR_CREATE_USER_SUCCESS';

export const LOG_OUT = 'LOG_OUT';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const GET_KEY_SUCCESS = 'GET_KEY_SUCCESS';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const SHOW_FLIGHTS = 'SHOW_FLIGHTS';